mutation BoardAdd($title: String!, $color: String!, $ownerId: ID!) {
    boardAdd(title: $title, color: $color, owner_id: $ownerId) {
        id
        title
        color
        owner {
         id
        }
    }
}
